--SEQ2 컬럼 추가
ALTER TABLE "ISAMSDBA"."UWO_CTR_MTR_EXP_MSIT_QST" ADD ("SEQ2" NUMBER );
COMMENT ON COLUMN "ISAMSDBA"."UWO_CTR_MTR_EXP_MSIT_QST"."SEQ2" IS '순서';

-- SEQ 값 SEQ2로 이식
UPDATE "ISAMSDBA"."UWO_CTR_MTR_EXP_MSIT_QST" SET SEQ2 = SEQ;

-- SEQ 삭제
ALTER TABLE "ISAMSDBA"."UWO_CTR_MTR_EXP_MSIT_QST" DROP ("SEQ");

-- SEQ2를 SEQ로 변경
ALTER TABLE "ISAMSDBA"."UWO_CTR_MTR_EXP_MSIT_QST" RENAME COLUMN "SEQ2" TO "SEQ";