CREATE TABLE "ISAMSDBA"."UWO_SA_CRITERION_POINT" (
    "USCP_BCY_COD" VARCHAR2(10) NOT NULL,
    "USCP_KIND_COD" VARCHAR2(30) NOT NULL,
    "USCP_KIND_POINT" NUMBER(1) NOT NULL,
    "USCP_P1_VAL" VARCHAR2(10),
    "USCP_P1_OP" VARCHAR2(5),
    "USCP_P2_VAL" VARCHAR2(10),
    "USCP_P2_OP" VARCHAR2(5),
    "CREATED_AT"  DATE,
    "UPDATED_AT"  DATE,
    CONSTRAINT UWO_SA_CRITERION_POINT PRIMARY KEY (USCP_BCY_COD, USCP_KIND_COD, USCP_KIND_POINT)
);

COMMENT ON TABLE "ISAMSDBA"."UWO_SA_CRITERION_POINT" IS 'SA 평가 점수별 구간';
COMMENT ON COLUMN "ISAMSDBA"."UWO_SA_CRITERION_POINT"."USCP_BCY_COD" IS '주기 코드';
COMMENT ON COLUMN "ISAMSDBA"."UWO_SA_CRITERION_POINT"."USCP_KIND_COD" IS '종류 코드';
COMMENT ON COLUMN "ISAMSDBA"."UWO_SA_CRITERION_POINT"."USCP_KIND_POINT" IS '점수';
COMMENT ON COLUMN "ISAMSDBA"."UWO_SA_CRITERION_POINT"."USCP_P1_VAL" IS '구간1 값';
COMMENT ON COLUMN "ISAMSDBA"."UWO_SA_CRITERION_POINT"."USCP_P1_OP" IS '구간1 연산자';
COMMENT ON COLUMN "ISAMSDBA"."UWO_SA_CRITERION_POINT"."USCP_P2_VAL" IS '구간2 값';
COMMENT ON COLUMN "ISAMSDBA"."UWO_SA_CRITERION_POINT"."USCP_P2_OP" IS '구간2 연산자';
COMMENT ON COLUMN "ISAMSDBA"."UWO_SA_CRITERION_POINT"."CREATED_AT" IS '생성일';
COMMENT ON COLUMN "ISAMSDBA"."UWO_SA_CRITERION_POINT"."UPDATED_AT" IS '수정일';