-- SA 점검레벨 기준별 구간범위
-- 증적자료 구간 변경
DELETE FROM UWO_SA_CRITERION_POINT WHERE USCP_BCY_COD='19' AND USCP_KIND_COD='inc';

INSERT INTO"UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'inc', '1', NULL, NULL, '20', 'lte', SYSDATE, SYSDATE);

INSERT INTO "UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'inc', '2', '20', 'lt', '40', 'lte', SYSDATE, SYSDATE);

INSERT INTO "UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'inc', '3', '40', 'lt', '60', 'lte', SYSDATE, SYSDATE);

INSERT INTO "UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'inc', '4', '60', 'lt', '80', 'lte', SYSDATE, SYSDATE);

INSERT INTO "UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'inc', '5', '80', 'lt', NULL, NULL, SYSDATE, SYSDATE);
