CREATE TABLE "ISAMSDBA"."UWO_DEP_SA"
(   "UDS_BCY_COD" VARCHAR2(10) NOT NULL,
    "UDS_DEP_COD" VARCHAR2(20) NOT NULL,
    "UDS_SA_LEVEL" VARCHAR2(10) NOT NULL,
    "UDS_WRK_KEY" NUMBER(10) NOT NULL,
    "CREATED_AT"  DATE,
    "UPDATED_AT"  DATE,
    CONSTRAINT UWO_DEP_SA_PK
        PRIMARY KEY (UDS_BCY_COD, UDS_DEP_COD)
);

COMMENT ON TABLE "ISAMSDBA"."UWO_DEP_SA" IS '부서별 보안등급';
COMMENT ON COLUMN "ISAMSDBA"."UWO_DEP_SA"."UDS_BCY_COD" IS '주기 코드';
COMMENT ON COLUMN "ISAMSDBA"."UWO_DEP_SA"."UDS_DEP_COD" IS '부서 코드';
COMMENT ON COLUMN "ISAMSDBA"."UWO_DEP_SA"."UDS_SA_LEVEL" IS '수정 보안레벨';
COMMENT ON COLUMN "ISAMSDBA"."UWO_DEP_SA"."UDS_WRK_KEY" IS '작업자 식별번호';
COMMENT ON COLUMN "ISAMSDBA"."UWO_DEP_SA"."CREATED_AT" IS '생성일';
COMMENT ON COLUMN "ISAMSDBA"."UWO_DEP_SA"."UPDATED_AT" IS '수정일';
