CREATE TABLE "ISAMSDBA"."UWO_SA_CRITERION" (
    "USC_BCY_COD" VARCHAR2(10) NOT NULL,
    "USC_KIND_COD" VARCHAR2(30) NOT NULL,
    "USC_KIND_TITLE" VARCHAR2(30) NOT NULL,
    "USC_USE" VARCHAR2(2) NOT NULL,
    "CREATED_AT"  DATE,
    "UPDATED_AT"  DATE,
    CONSTRAINT UWO_SA_CRITERION PRIMARY KEY (USC_BCY_COD, USC_KIND_COD)
);

COMMENT ON TABLE "ISAMSDBA"."UWO_SA_CRITERION" IS 'SA 평가 기준';
COMMENT ON COLUMN "ISAMSDBA"."UWO_SA_CRITERION"."USC_BCY_COD" IS '주기 코드';
COMMENT ON COLUMN "ISAMSDBA"."UWO_SA_CRITERION"."USC_KIND_COD" IS '종류 코드';
COMMENT ON COLUMN "ISAMSDBA"."UWO_SA_CRITERION"."USC_KIND_TITLE" IS '종류명';
COMMENT ON COLUMN "ISAMSDBA"."UWO_SA_CRITERION"."USC_USE" IS '사용여부';
COMMENT ON COLUMN "ISAMSDBA"."UWO_SA_CRITERION"."CREATED_AT" IS '생성일';
COMMENT ON COLUMN "ISAMSDBA"."UWO_SA_CRITERION"."UPDATED_AT" IS '수정일';