CREATE TABLE "ISAMSDBA"."UWO_COM_COD_EXP_STND_KIND"
(   "SND_COD" VARCHAR2(255) ,
    "KIND" VARCHAR2(255) ,
    PRIMARY KEY ("SND_COD")
);

COMMENT ON TABLE "ISAMSDBA"."UWO_COM_COD_EXP_STND_KIND" IS '통제항목표준명 확장테이블';
COMMENT ON COLUMN "ISAMSDBA"."UWO_COM_COD_EXP_STND_KIND"."SND_COD" IS '통제항목표준명 코드';
COMMENT ON COLUMN "ISAMSDBA"."UWO_COM_COD_EXP_STND_KIND"."KIND" IS '룰 타입';
