-- SA 점검레벨 기준별 구간범위
-- 증적자료
INSERT INTO "ISAMSDBA"."UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'inc', '1', '0', 'eq', NULL, NULL, SYSDATE, SYSDATE);

INSERT INTO "ISAMSDBA"."UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'inc', '2', '0', 'lt', '20', 'lte', SYSDATE, SYSDATE);

INSERT INTO "ISAMSDBA"."UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'inc', '3', '20', 'lt', '60', 'lte', SYSDATE, SYSDATE);

INSERT INTO "ISAMSDBA"."UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'inc', '4', '60', 'lt', '100', 'lte', SYSDATE, SYSDATE);

INSERT INTO "ISAMSDBA"."UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'inc', '5', '100', 'lt', NULL, NULL, SYSDATE, SYSDATE);

-- N/A 과다
INSERT INTO "ISAMSDBA"."UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'na', '1', '50', 'lte', NULL, NULL, SYSDATE, SYSDATE);

INSERT INTO "ISAMSDBA"."UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'na', '2', '40', 'lte', '50', 'lt', SYSDATE, SYSDATE);

INSERT INTO "ISAMSDBA"."UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'na', '3', '30', 'lte', '40', 'lt', SYSDATE, SYSDATE);

INSERT INTO "ISAMSDBA"."UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'na', '4', '20', 'lt', '30', 'lt', SYSDATE, SYSDATE);

INSERT INTO "ISAMSDBA"."UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'na', '5', NULL, NULL, '20', 'lte', SYSDATE, SYSDATE);

-- 진척도
INSERT INTO "ISAMSDBA"."UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'prog', '1', NULL, NULL, '60', 'lte', SYSDATE, SYSDATE);

INSERT INTO "ISAMSDBA"."UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'prog', '2', '60', 'lt', '80', 'lte', SYSDATE, SYSDATE);

INSERT INTO "ISAMSDBA"."UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'prog', '3', '80', 'lt', '90', 'lte', SYSDATE, SYSDATE);

INSERT INTO "ISAMSDBA"."UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'prog', '4', '90', 'lt', '95', 'lte', SYSDATE, SYSDATE);

INSERT INTO "ISAMSDBA"."UWO_SA_CRITERION_POINT" ("USCP_BCY_COD", "USCP_KIND_COD", "USCP_KIND_POINT", "USCP_P1_VAL", "USCP_P1_OP", "USCP_P2_VAL", "USCP_P2_OP", "CREATED_AT", "UPDATED_AT")
VALUES ('19', 'prog', '5', '95', 'lt', '100', 'lte', SYSDATE, SYSDATE);
