CREATE TABLE "ISAMSDBA"."POPUP"
(	"POPUP_ID" NUMBER(10,0) NOT NULL ENABLE,
	"BRD_KEY" NUMBER(10,0),
	"STATUS" CHAR(1) DEFAULT 'N',
	"START_DATE" DATE DEFAULT NULL,
	"FINISH_DATE" DATE DEFAULT NULL,
	"WIDTH" NUMBER(4,0) DEFAULT NULL,
	"HEIGHT" NUMBER(4,0) DEFAULT NULL,
	"TOP" NUMBER(4,0) DEFAULT NULL,
	"LEFT" NUMBER(4,0) DEFAULT NULL,
	 PRIMARY KEY ("POPUP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--   TABLESPACE "ISAMS"  ENABLE
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT);
-- TABLESPACE "ISAMS";

COMMENT ON TABLE "ISAMSDBA"."POPUP" IS '팝업테이블' ;
COMMENT ON COLUMN "ISAMSDBA"."POPUP"."POPUP_ID" IS '팝업 ID';
COMMENT ON COLUMN "ISAMSDBA"."POPUP"."BRD_KEY" IS '게시물 KEY';
COMMENT ON COLUMN "ISAMSDBA"."POPUP"."STATUS" IS '사용여부';
COMMENT ON COLUMN "ISAMSDBA"."POPUP"."START_DATE" IS '시작일';
COMMENT ON COLUMN "ISAMSDBA"."POPUP"."FINISH_DATE" IS '종료일';
COMMENT ON COLUMN "ISAMSDBA"."POPUP"."WIDTH" IS '크기-가로(px)';
COMMENT ON COLUMN "ISAMSDBA"."POPUP"."HEIGHT" IS '크기-세로(px)';
COMMENT ON COLUMN "ISAMSDBA"."POPUP"."TOP" IS '위치-상단(px)';
COMMENT ON COLUMN "ISAMSDBA"."POPUP"."LEFT" IS '위치-좌측(px)';