-- SA 점검레벨 기준 값
-- 증적자료
INSERT INTO "ISAMSDBA"."UWO_SA_CRITERION" ("USC_BCY_COD", "USC_KIND_COD", "USC_KIND_TITLE", "USC_USE", "CREATED_AT", "UPDATED_AT" )
VALUES ('19', 'inc', '증적자료', 'y', SYSDATE, SYSDATE );

-- N/A 과다
INSERT INTO "ISAMSDBA"."UWO_SA_CRITERION" ("USC_BCY_COD", "USC_KIND_COD", "USC_KIND_TITLE", "USC_USE", "CREATED_AT", "UPDATED_AT" )
VALUES ('19', 'na', 'N/A 과다', 'y', SYSDATE, SYSDATE );

-- 진척도
INSERT INTO "ISAMSDBA"."UWO_SA_CRITERION" ("USC_BCY_COD", "USC_KIND_COD", "USC_KIND_TITLE", "USC_USE", "CREATED_AT", "UPDATED_AT" )
VALUES ('19', 'prog', '진척도', 'y', SYSDATE, SYSDATE );

